#!/bin/bash

echo "=========================================="
echo "POST AD FORM - VALIDATION ERROR TEST"
echo "=========================================="
echo ""

# Check if app is running
echo "1. Checking if application is accessible..."
if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep -q "200\|302"; then
    echo "   ✅ Application is running"
else
    echo "   ❌ Application not accessible at localhost:8000"
    echo "   Please start the application first:"
    echo "   cd /home/www/laravel/marketplace && php artisan serve"
    exit 1
fi

echo ""
echo "2. Test scenarios to verify manually:"
echo ""
echo "=========================================="
echo "TEST 1: Basic Form Value Retention"
echo "=========================================="
echo "Steps:"
echo "  1. Navigate to: http://localhost:8000/user/post-ad"
echo "  2. Fill in:"
echo "     - Ad Title: 'Test Car for Sale'"
echo "     - Category: Select 'Vehicles'"
echo "     - Subcategory: Select 'Cars'"
echo "     - Brand: Select any brand"
echo "     - Price: '5000000'"
echo "     - State: 'Lagos'"
echo "     - LGA: 'Ikeja'"
echo "  3. Leave DESCRIPTION empty"
echo "  4. Click 'Post Ad'"
echo ""
echo "Expected Result:"
echo "  ✅ Validation error: 'Description is required'"
echo "  ✅ Title still shows 'Test Car for Sale'"
echo "  ✅ Category still shows 'Vehicles'"
echo "  ✅ Subcategory still shows 'Cars'"
echo "  ✅ Brand still selected"
echo "  ✅ Price still shows '5,000,000'"
echo "  ✅ State still shows 'Lagos'"
echo "  ✅ LGA still shows 'Ikeja'"
echo ""

echo "=========================================="
echo "TEST 2: Image Retention"
echo "=========================================="
echo "Steps:"
echo "  1. Same as Test 1, but also:"
echo "  2. Upload 2-3 test images"
echo "  3. Submit without description"
echo ""
echo "Expected Result:"
echo "  ✅ All form values retained (as in Test 1)"
echo "  ✅ Image previews shown with thumbnails"
echo "  ✅ Green message: 'Your images are retained!'"
echo "  ✅ Shows count: '3 image(s) you uploaded are still here'"
echo "  ✅ Each image has delete (×) button"
echo ""

echo "=========================================="
echo "TEST 3: Car-Specific Fields"
echo "=========================================="
echo "Steps:"
echo "  1. Select Category: Vehicles → Subcategory: Cars"
echo "  2. Fill car-specific fields:"
echo "     - Vehicle Condition: 'Foreign used'"
echo "     - Fuel: 'Petrol'"
echo "     - Transmission: 'Automatic'"
echo "     - Body Type: 'SUV/Off Road Vehicle'"
echo "     - Check: 'Air conditioning', 'Bluetooth'"
echo "  3. Submit without description"
echo ""
echo "Expected Result:"
echo "  ✅ Vehicle Condition still shows 'Foreign used'"
echo "  ✅ Fuel still shows 'Petrol'"
echo "  ✅ Transmission still shows 'Automatic'"
echo "  ✅ Body Type still shows 'SUV/Off Road Vehicle'"
echo "  ✅ Air conditioning checkbox still checked"
echo "  ✅ Bluetooth checkbox still checked"
echo ""

echo "=========================================="
echo "TEST 4: Multiple Validation Errors"
echo "=========================================="
echo "Steps:"
echo "  1. Fill only Title: 'Test Item'"
echo "  2. Upload 2 images"
echo "  3. Submit (missing category, subcategory, brand, etc.)"
echo "  4. Fix category, subcategory, brand"
echo "  5. Submit again (still missing description)"
echo "  6. Finally add description"
echo "  7. Submit"
echo ""
echo "Expected Result:"
echo "  ✅ After 1st error: Title + images retained"
echo "  ✅ After 2nd error: Title + category + subcategory + brand + images retained"
echo "  ✅ After fixing: Ad successfully created with all data and images"
echo ""

echo "=========================================="
echo "TEST 5: Shipment & Buy Direct"
echo "=========================================="
echo "Steps:"
echo "  1. Select 'Shipping Possible'"
echo "  2. Check 2 shipping carriers"
echo "  3. Select 'Enable Buy Direct'"
echo "  4. Submit without description"
echo ""
echo "Expected Result:"
echo "  ✅ 'Shipping Possible' still selected"
echo "  ✅ Shipping carriers dropdown still visible"
echo "  ✅ Both shipping carriers still checked"
echo "  ✅ 'Enable Buy Direct' still selected"
echo ""

echo "=========================================="
echo "TEST 6: Remove Temp Images"
echo "=========================================="
echo "Steps:"
echo "  1. Upload 4 images"
echo "  2. Submit with validation error"
echo "  3. See 4 temp image previews"
echo "  4. Click delete (×) on 2nd image"
echo "  5. Add description"
echo "  6. Submit"
echo ""
echo "Expected Result:"
echo "  ✅ After delete: Only 3 images shown"
echo "  ✅ Success message updates to '3 image(s)'"
echo "  ✅ After submit: Ad created with only 3 images (2nd one excluded)"
echo ""

echo "=========================================="
echo "AUTOMATED CHECKS"
echo "=========================================="
echo ""

# Check if temp directory exists
echo "3. Checking temp directory setup..."
if [ -d "/home/www/laravel/marketplace/storage/app/public/temp" ]; then
    echo "   ✅ Temp directory exists"
else
    echo "   ⚠️  Temp directory not yet created (will be created on first upload)"
fi

# Check if routes are accessible
echo ""
echo "4. Checking route accessibility..."
curl -s http://localhost:8000/user/post-ad > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "   ✅ Post ad route accessible"
else
    echo "   ⚠️  Post ad route may require login"
fi

echo ""
echo "5. Checking for recent code changes..."
if grep -q "storeTemporaryImages" /home/www/laravel/marketplace/app/Http/Controllers/UserManageAdverts.php; then
    echo "   ✅ Image retention code present in controller"
else
    echo "   ❌ Image retention code NOT found in controller"
fi

if grep -q "temp_images" /home/www/laravel/marketplace/resources/views/dashboard/post-ad.blade.php; then
    echo "   ✅ Temp image display code present in view"
else
    echo "   ❌ Temp image display code NOT found in view"
fi

if grep -q "data-old-value" /home/www/laravel/marketplace/resources/views/dashboard/post-ad.blade.php; then
    echo "   ✅ Form value retention code present in view"
else
    echo "   ❌ Form value retention code NOT found in view"
fi

echo ""
echo "=========================================="
echo "MANUAL TESTING REQUIRED"
echo "=========================================="
echo ""
echo "Please manually test the scenarios above and verify:"
echo ""
echo "✅ CHECKLIST:"
echo "  [ ] All text inputs retain values on validation error"
echo "  [ ] All select dropdowns retain selections"
echo "  [ ] All radio buttons retain selections"
echo "  [ ] All checkboxes retain checked state"
echo "  [ ] Category → Subcategory → Brand → Model chain restored"
echo "  [ ] State → LGA chain restored"
echo "  [ ] Uploaded images displayed as previews"
echo "  [ ] Can remove temp images"
echo "  [ ] Can add more images after error"
echo "  [ ] Success message shows for retained images"
echo "  [ ] Final submission works with all data + images"
echo ""
echo "=========================================="
echo "To start application (if not running):"
echo "  cd /home/www/laravel/marketplace"
echo "  php artisan serve"
echo "=========================================="
